# Generated by Django 4.1.3 on 2022-11-07 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autore',
            options={'verbose_name': 'Atore', 'verbose_name_plural': 'Autori'},
        ),
        migrations.AlterModelOptions(
            name='genere',
            options={'verbose_name': 'Genere', 'verbose_name_plural': 'Generi'},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name': 'Libro', 'verbose_name_plural': 'Libri'},
        ),
    ]
